/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GlobalKeyListener2 */

#ifndef _Included_GlobalKeyListener2
#define _Included_GlobalKeyListener2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GlobalKeyListener2
 * Method:    startListening
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GlobalKeyListener2_startListening
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
