/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GlobalKeyListener */

#ifndef _Included_GlobalKeyListener
#define _Included_GlobalKeyListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GlobalKeyListener
 * Method:    startListening
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GlobalKeyListener_startListening
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
